const basic = [
	{
		name: "Amplifying Tome",
		type: "basic",
		class: ["mage", "support"],
		cost: 435,
		icon: "Amplifying_Tome_item.png",
		stats: ["+20 Ability Power"],
		description: ["", ""],
	},
	{
		name: "B. F. Sword",
		type: "basic",
		class: ["fighter", "marksman", "assassin"],
		cost: 1300,
		icon: "B._F._Sword_item.png",
		stats: ["+40 Attack Damage"],
		description: ["", ""],
	},
	{
		name: "Blasting Wand",
		type: "basic",
		class: ["mage", "support"],
		cost: 850,
		icon: "Blasting_Wand_item.png",
		stats: ["+40 Ability Power"],
		description: ["", ""],
	},
	{
		name: "Cloak of Agility",
		type: "basic",
		class: ["marksman"],
		cost: 600,
		icon: "Cloak_of_Agility_item.png",
		stats: ["+15% Critical Strike Chance"],
		description: ["", ""],
	},
	{
		name: "Cloth Armor",
		type: "basic",
		class: ["mage", "support", "fighter", "marksman", "assassin", "tank"],
		cost: 300,
		icon: "Cloth_Armor_item.png",
		stats: ["+15 Armor"],
		description: ["", ""],
	},
	{
		name: "Dagger",
		type: "basic",
		class: ["mage", "support"],
		cost: 250,
		icon: "Dagger_item.png",
		stats: ["+50% Base Mana Regeneration"],
		description: ["", ""],
	},
	{
		name: "Faerie Charm",
		type: "basic",
		class: ["mage", "support"],
		cost: 435,
		icon: "Faerie_Charm_item.png",
		stats: ["+20 Ability Power"],
		description: ["", ""],
	},
	{
		name: "Long Sword",
		type: "basic",
		class: ["fighter", "marksman", "assassin"],
		cost: 350,
		icon: "Long_Sword_item.png",
		stats: ["+10 Attack Damage"],
		description: ["", ""],
	},
	{
		name: "Needlessly Large Rod",
		type: "basic",
		class: ["mage", "support"],
		cost: 435,
		icon: "Needlessly_Large_Rod_item.png",
		stats: ["+60 Ability Power"],
		description: ["", ""],
	},
	{
		name: "Null-Magic Mantle",
		type: "basic",
		class: ["fighter", "marksman", "assassin", "mage", "tank", "support"],
		cost: 450,
		icon: "Null-Magic_Mantle_item.png",
		stats: ["+25 Magic Resistance"],
		description: ["", ""],
	},
	{
		name: "Amplifying Tome",
		type: "basic",
		class: ["mage", "support"],
		cost: 435,
		icon: "Amplifying_Tome_item.png",
		stats: ["+20 Ability Power"],
		description: ["", ""],
	},
	{
		name: "Pickaxe",
		type: "basic",
		class: ["fighter", "marksman", "assassin"],
		cost: 875,
		icon: "Pickaxe_item.png",
		stats: ["+25 Attack Damage"],
		description: ["", ""],
	},
	{
		name: "Rejuvenation Bead",
		type: "basic",
		class: ["tank"],
		cost: 150,
		icon: "Rejuvenation_Bead_item.png",
		stats: ["+50% base health regeneration"],
		description: ["", ""],
	},
	{
		name: "Ruby Crystal",
		type: "basic",
		class: ["fighter", "marksman", "assassin", "mage", "tank", "support"],
		cost: 400,
		icon: "Ruby_Crystal_item.png",
		stats: ["+150 Health"],
		description: ["", ""],
	},
	{
		name: "Sapphire Crystal",
		type: "basic",
		class: ["mage", "tank"],
		cost: 350,
		icon: "Sapphire_Crystal_item.png",
		stats: ["+250 Mana"],
		description: ["", ""],
	},
	{
		name: "Sheen",
		type: "basic",
		class: ["fighter", "marksman", "mage"],
		cost: 700,
		icon: "Sheen_item.png",
		stats: [""],
		description: [
			"UNIQUE – SPELLBLADE: After using an ability, your next basic attack within 10 seconds deals 100% base AD bonus physical damage on-hit (1.5 (begins after using the empowered attack) second cooldown).",
			"",
		],
	},
	{
		name: "Stopwatch",
		type: "basic",
		class: ["fighter", "marksman", "assassin", "mage"],
		cost: 650,
		icon: "Stopwatch_item.png",
		stats: [""],
		description: [
			"UNIQUE – STASIS: Put yourself in stasis for 2.5 seconds, rendering you untargetable and invulnerable for the duration but also unable to move, declare basic attacks, cast abilities, use summoner spells, or activate items.",
			"Transforms into Broken Stopwatch when activated, which cannot be activated again. Once broken, all future purchases are also broken.",
		],
	},
];

export { basic };
