const starter = [
	{
		name: "Dark Seal",
		type: "starter",
		class: ["starter"],
		cost: 350,
		icon: "Dark_Seal_item.png",
		stats: ["+15 Ability Power", "+40 Health"],
		description: [
			"UNIQUE – GLORY: Gain 2 stacks for each champion kill and 1 stack for each assist, up to a maximum of 10 stacks. Lose 5 stacks on death. Stacks are preserved when upgrading to Mejai's Soulstealer.",
			"UNIQUE – DREAD: Gain 4 ability power for each stack of Glory.",
		],
	},
	{
		name: "Cull",
		type: "starter",
		class: ["fighter", "marksman", "assassin"],
		cost: 450,
		icon: "Cull_item.png",
		stats: ["+7 Attack damage", "+3 Health on-hit"],
		description: [
			"UNIQUE – REAP: Killing a minion grants 1 gold, up to a maximum of 100 gold. After having killed 100 minions, grants an additional 350 Gold 350 and permanently disables this passive.",
			"",
		],
	},
	{
		name: "Doran's Bladee",
		type: "starter",
		class: ["fighter", "marksman", "assassin"],
		cost: 450,
		icon: "Doran_Blade_item.png",
		stats: ["+8 Attack damage", "+30 Health"],
		description: ["UNIQUE – WARMONGER: +2.5% omnivamp", ""],
	},
	{
		name: "Doran's Ring",
		type: "starter",
		class: ["mage"],
		cost: 450,
		icon: "Doran_Ring_item.png",
		stats: ["+15 Ability Power", "+70 Health"],
		description: [
			"UNIQUE – FOCUS: Basic attacks deal 5 bonus physical damage on-hit against Minion icon.png minions.",
			"UNIQUE – DRAIN: Restore 0.75 mana every second, increased to 1.25 for 10 seconds when you damage an enemy champion. If you can't gain mana, heal 50% of this value instead.",
		],
	},
	{
		name: "Doran's Shield",
		type: "starter",
		class: ["fighter", "marksman", "assassin", "mage", "tank"],
		cost: 450,
		icon: "Doran_Shield_item.png",
		stats: ["+80 Health", "+6 Health Per 5 Seconds"],
		description: [
			"UNIQUE – FOCUS: Basic attacks deal 5 bonus physical damage on-hit against minions.",
			"UNIQUE – ENDURE: After taking damage from a champion or large monster, gain health regeneration equal to 0 − 40 (based on current missing health) health over 8 seconds. Reduced to 66% effectiveness on ranged champions or when triggered by AoE, DoT or proc effects.",
		],
	},
	{
		name: "Relic Shield",
		type: "starter",
		class: ["tank", "support"],
		cost: 400,
		icon: "Relic_Shield_item.png",
		stats: [
			"+5 Ability Power",
			"+30 Health",
			"+25% Base Health Regeneration",
			"+2 Gold Per 10 Seconds",
		],
		description: [
			"UNIQUE – SPOILS OF WAR: Grants a charge every 35 seconds, up to 3 charges. Basic attacks can consume a charge to execute minions. Basic attacks execute minions below (Melee 50% / Ranged 30%) of their maximum health. Killing a minion by any means with a charge grants you and the nearest allied champion kill gold. These effects require an allied champion to be nearby. Receive diminishing gold from excessive minion kills.",
			"UNIQUE – QUEST: Earn 500 gold using this item to upgrade to Targon's Buckler, gaining the WARDING active with 3 wards in stock.",
		],
	},
	{
		name: "Spectral Sickle",
		type: "starter",
		class: ["support"],
		cost: 400,
		icon: "Spectral_Sickle_item.png",
		stats: [
			"+5 Attack Damage",
			"+10 Health",
			"+25% Base Mana Regeneration",
			"+2 Gold Per 10 seconds",
		],
		description: [
			"UNIQUE – TRIBUTE: Grants a charge every 10 seconds, up to 3 charges. If an allied champion is nearby, damaging abilities and attacks against champions and structures consume a charge, up to one per attack or cast. Consuming a charge grants 20 gold. Receive diminishing gold from excessive minion kills.",
			"UNIQUE – QUEST: Earn 500 gold using this item to upgrade to Harrowing Crescent, gaining the WARDING active with 3 wards in stock.",
		],
	},
	{
		name: "Spellthief's Edge",
		type: "starter",
		class: ["mage", "support"],
		cost: 400,
		icon: "Spellthief_Edge_item.png",
		stats: [
			"+8 Ability Power",
			"+10 Health",
			"+50% Base Mana Regeneration",
			"+2 Gold Per 10 seconds",
		],
		description: [
			"UNIQUE – TRIBUTE: Grants a charge every 10 seconds, up to 3 charges. If an allied champion is nearby, damaging abilities and attacks against champions and structures consume a charge, up to one per attack or cast. Consuming a charge grants 20 gold. Receive diminishing gold from excessive minion kills.",
			"UNIQUE – QUEST: Earn 500 gold using this item to upgrade to Frostfang, gaining the WARDING active with 3 wards in stock.",
		],
	},
	{
		name: "Steel Shoulderguards",
		type: "starter",
		class: ["tank"],
		cost: 400,
		icon: "Steel_Shoulderguards_item.png",
		stats: [
			"+3 Attack Damage",
			"+30 Health",
			"+25% Base Health Regeneration",
			"+2 Gold Per 10 Seconds",
		],
		description: [
			"UNIQUE – SPOILS OF WAR: Grants a charge every 35 seconds, up to 3 charges. Basic attacks can consume a charge to execute minions. Basic attacks  execute minions below (Melee 50% / Ranged 30%) of their maximum health. Killing a minion by any means with a charge grants you and the nearest allied champion kill gold. These effects require an allied champion to be nearby. Receive diminishing gold from excessive minion kills.",
			"UNIQUE – QUEST: Earn 500 Gold 500 using this item to upgrade to Runesteel Spaulders, gaining the WARDING active with 3 wards in stock.",
		],
	},
	{
		name: "Tear of the Goddess",
		type: "starter",
		class: ["mage", "marksman"],
		cost: 400,
		icon: "Tear_of_the_Goddess_item.png",
		stats: ["+240 Mana"],
		description: [
			"UNIQUE – FOCUS: Basic attacks deal 5 bonus physical damage on-hit against minions.",
			"UNIQUE – MANA CHARGE: Grants a charge every 8 seconds, up to 4 charges. Affecting an enemy or ally with an ability consumes a charge and grants 3 bonus mana, increased to 6 if it's a champion, up to maximum of 360 bonus mana.",
		],
	},
];

export { starter };
